export type SpecLevel = "MUST" | "SHOULD" | "MAY";
export type SpecScope = "in-scope" | "excluded" | "n/a";
export type CoverageStatus = "covered" | "partial" | "missing" | "failing";
export type EvidenceQuality = "strict" | "partial" | "weak";
export type ScenarioKind = "unit" | "integration" | "contract";

export interface EvidenceRef {
  readonly test: string;
  readonly quality: EvidenceQuality;
  readonly notes?: string;
}

export interface SpecScenario {
  readonly id: string;
  readonly feature: string;
  readonly kind: ScenarioKind;
  readonly description: string;
  readonly clauses: ReadonlyArray<string>;
  readonly evidence: ReadonlyArray<EvidenceRef>;
  readonly status: CoverageStatus;
}

export interface SpecClause {
  readonly id: string;
  readonly section: string;
  readonly title: string;
  readonly level: SpecLevel;
  readonly scope: SpecScope;
  readonly feature: string;
  readonly status: CoverageStatus;
  readonly text: string;
  readonly scenarios: ReadonlyArray<string>;
  readonly evidence: ReadonlyArray<EvidenceRef>;
  readonly missingCases?: ReadonlyArray<string>;
  readonly notes?: string;
}

export const excludedSpecAreas = [
  { section: "5.3.6", feature: "ai-gateway", reason: "Explicitly out of scope for current SDK" },
  { section: "5.3.7", feature: "gateway-http-fetch", reason: "Explicitly out of scope for current SDK" },
  { section: "6", feature: "middleware", reason: "Explicitly out of scope for current SDK" },
  { section: "8", feature: "connect", reason: "Explicitly out of scope for current SDK" },
  { section: "9", feature: "streaming", reason: "Explicitly out of scope for current SDK" },
  {
    section: "10.3.2",
    feature: "sync-checkpointing",
    reason: "Requires durable endpoint primitive — out of scope for current SDK",
  },
  {
    section: "10.4.2",
    feature: "sync-checkpointing-flow",
    reason: "Requires durable endpoint primitive — out of scope for current SDK",
  },
] as const;

export const scenarios: ReadonlyArray<SpecScenario> = [
  {
    id: "env.layer-from-env.basic",
    feature: "env",
    kind: "unit",
    description: "Loads app id and signing keys from environment-backed config",
    clauses: ["3.1-event-key", "3.1-signing-key", "3.1-signing-key-fallback"],
    status: "partial",
    evidence: [{ test: "test/unit/client.test.ts :: layerFromEnv creates layer from environment", quality: "partial" }],
  },
  {
    id: "signature.dev-bypass",
    feature: "signature",
    kind: "unit",
    description: "Dev mode bypasses signature verification",
    clauses: ["4.1.3-dev-bypass", "4.2.2-dev-disables-verification"],
    status: "covered",
    evidence: [
      { test: "test/unit/signature.test.ts :: bypasses verification when isDev is true", quality: "strict" },
      {
        test: "test/unit/signature.test.ts :: bypasses verification even with invalid signature in dev mode",
        quality: "strict",
      },
    ],
  },
  {
    id: "signature.validation-matrix",
    feature: "signature",
    kind: "unit",
    description: "Primary validation matrix for signature header, timestamp, hmac, and fallback key",
    clauses: [
      "4.1.3-missing-signing-key",
      "4.1.3-missing-header",
      "4.1.3-expired-header",
      "4.1.3-invalid-format",
      "4.1.3-invalid-signature",
      "3.1-signing-key-fallback",
    ],
    status: "covered",
    evidence: [
      { test: "test/unit/signature.test.ts :: succeeds with valid signature", quality: "strict" },
      { test: "test/unit/signature.test.ts :: fails with missing signing key", quality: "strict" },
      { test: "test/unit/signature.test.ts :: fails with missing signature header", quality: "strict" },
      { test: "test/unit/signature.test.ts :: fails with invalid signature format", quality: "strict" },
      { test: "test/unit/signature.test.ts :: fails with expired signature (> 5 minutes old)", quality: "strict" },
      { test: "test/unit/signature.test.ts :: fails with future signature (> 5 minutes ahead)", quality: "strict" },
      { test: "test/unit/signature.test.ts :: fails with invalid signature (wrong key)", quality: "strict" },
      {
        test: "test/unit/signature.test.ts :: succeeds when primary key fails but fallback matches",
        quality: "strict",
      },
    ],
  },
  {
    id: "sync.registration-core",
    feature: "sync",
    kind: "integration",
    description: "PUT request triggers /fn/register with the expected registration payload",
    clauses: ["4.3.1-sync-response-shape", "4.3.2-register-post", "4.3.2-register-payload", "4.3.2-step-runtime-url"],
    status: "partial",
    evidence: [
      {
        test: "test/integration/registration.test.ts :: PUT / triggers registration POST to Inngest",
        quality: "strict",
      },
      {
        test: "test/integration/registration.test.ts :: includes expression field for triggers with if condition",
        quality: "strict",
      },
      {
        test: "test/integration/registration.test.ts :: step URL includes fnId and stepId query parameters",
        quality: "strict",
      },
    ],
  },
  {
    id: "sync.registration-failure",
    feature: "sync",
    kind: "integration",
    description: "Registration failure propagates back through the PUT handler",
    clauses: ["4.3.3-sync-failure", "4.3.4-sync-success-modified"],
    status: "partial",
    evidence: [
      { test: "test/integration/registration.test.ts :: handles registration failure gracefully", quality: "partial" },
      { test: "test/unit/handler.test.ts :: handles registration HTTP error", quality: "partial" },
    ],
  },
  {
    id: "call.simple-success",
    feature: "call",
    kind: "integration",
    description: "A simple function call returns 200 JSON",
    clauses: ["4.4.3-call-success", "4.4.3-call-context"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/hello-world.test.ts :: executes function and returns 200 with result",
        quality: "strict",
      },
      {
        test: "test/integration/functiongroup-http.test.ts :: executes function and returns result",
        quality: "strict",
      },
    ],
  },
  {
    id: "call.query-errors",
    feature: "call",
    kind: "integration",
    description: "Missing fnId and unknown function paths are rejected",
    clauses: ["4.4.1-missing-fnid", "4.4.1-unknown-function"],
    status: "partial",
    evidence: [
      { test: "test/integration/functiongroup-http.test.ts :: returns error when fnId is missing", quality: "partial" },
      {
        test: "test/integration/functiongroup-http.test.ts :: returns error when function not found",
        quality: "partial",
      },
      {
        test: "test/integration/functiongroup-http.test.ts :: returns error when handler not found",
        quality: "partial",
      },
    ],
  },
  {
    id: "call.invalid-body",
    feature: "call",
    kind: "integration",
    description: "Malformed JSON and invalid request schema are rejected",
    clauses: ["4.4.1-invalid-json", "4.4.1-invalid-body-schema"],
    status: "partial",
    evidence: [
      { test: "test/integration/functiongroup-http.test.ts :: returns 500 for invalid JSON body", quality: "partial" },
      {
        test: "test/integration/functiongroup-http.test.ts :: returns 500 for invalid request body schema",
        quality: "partial",
      },
    ],
  },
  {
    id: "call.stepid-precedence",
    feature: "call",
    kind: "integration",
    description: "URL stepId overrides body ctx.step_id",
    clauses: ["4.4.1-stepid-routing"],
    status: "covered",
    evidence: [
      { test: "test/integration/functiongroup-http.test.ts :: parses stepId from query params", quality: "strict" },
      {
        test: "test/integration/regression.test.ts :: specific stepId in URL causes that step to execute",
        quality: "strict",
      },
    ],
  },
  {
    id: "call.function-errors",
    feature: "call",
    kind: "integration",
    description: "Function-level retry and no-retry paths set status and headers",
    clauses: ["4.4.3-error-shape", "4.4.3-retriable-error", "4.4.3-nonretriable-error", "4.4.3-retry-after"],
    status: "partial",
    evidence: [
      {
        test: "test/integration/retry-after-error.test.ts :: returns 500 with Retry-After header for function-level retry",
        quality: "strict",
      },
      {
        test: "test/integration/regression.test.ts :: handler throwing NonRetriableError directly sets X-Inngest-No-Retry: true",
        quality: "partial",
      },
    ],
  },
  {
    id: "use-api.protocol-only",
    feature: "use_api",
    kind: "unit",
    description: "Schemas accept use_api payload shapes, but handler behavior is not exercised",
    clauses: ["4.4.2-use-api-batch", "4.4.2-use-api-actions", "4.4.2-use-api-failure"],
    status: "missing",
    evidence: [
      {
        test: "test/unit/useapi.test.ts :: Protocol types for UseApi",
        quality: "weak",
        notes: "Schema-only coverage; no behavior coverage",
      },
    ],
  },
  {
    id: "introspection.basic",
    feature: "introspection",
    kind: "integration",
    description: "GET introspection returns base fields and schema version",
    clauses: ["4.5-introspection-base", "4.5-introspection-schema-version"],
    status: "partial",
    evidence: [
      {
        test: "test/integration/functiongroup-http.test.ts :: returns introspection response with function count",
        quality: "strict",
      },
      {
        test: "test/integration/functiongroup-http.test.ts :: returns schema_version in introspection",
        quality: "strict",
      },
      {
        test: "test/integration/introspection.test.ts :: introspection response includes correct schema_version",
        quality: "strict",
      },
    ],
  },
  {
    id: "introspection-auth-and-functions",
    feature: "introspection",
    kind: "integration",
    description: "Dev/cloud introspection variants and authenticated fields",
    clauses: ["4.5-introspection-dev-functions", "4.5-introspection-authenticated"],
    status: "partial",
    evidence: [
      {
        test: "test/integration/introspection.test.ts :: GET / in dev mode returns functions array",
        quality: "partial",
        notes: "Test documents expected behavior, implementation currently omits functions",
      },
      {
        test: "test/integration/introspection.test.ts :: GET / in cloud mode does NOT include functions array",
        quality: "partial",
      },
    ],
  },
  {
    id: "step.run.discovery-and-replay",
    feature: "steps.run",
    kind: "integration",
    description: "step.run plans on first call and resumes from memoized data",
    clauses: ["5.1-step-response-shape", "5.1.3-decide-when-to-report", "5.2-step-memo-data", "5.3.1-step-run"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/step-memoization.test.ts :: returns 206 with StepPlanned on first invocation",
        quality: "strict",
      },
      {
        test: "test/integration/step-memoization.test.ts :: returns 200 with final result when step is memoized",
        quality: "strict",
      },
    ],
  },
  {
    id: "step.run.errors",
    feature: "steps.run",
    kind: "integration",
    description: "step.run emits StepError opcodes and propagates memoized failures",
    clauses: ["5.2-step-memo-error", "5.3.1-step-run-error", "4.4.3-retriable-error", "4.4.3-nonretriable-error"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/step-error-handling.test.ts :: re-raises error when memoized data has error property",
        quality: "strict",
      },
      {
        test: "test/integration/step-error-handling.test.ts :: emits StepError opcode when step.run fails",
        quality: "strict",
      },
      {
        test: "test/integration/step-error-handling.test.ts :: includes error stack in StepError opcode",
        quality: "strict",
      },
      {
        test: "test/integration/step-error-handling.test.ts :: catches unexpected defects and returns 500",
        quality: "strict",
      },
      {
        test: "test/integration/regression.test.ts :: step failure wraps NonRetriableError and sets noRetry in StepError opcode",
        quality: "strict",
      },
    ],
  },
  {
    id: "step.run-retry-after",
    feature: "steps.run",
    kind: "integration",
    description: "RetryAfterError inside step.run becomes a 206 StepError with Retry-After",
    clauses: ["4.4.3-retry-after", "5.3.1-step-run-error"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/retry-after-error.test.ts :: emits StepError opcode (206) - NOT function-level retry",
        quality: "strict",
      },
      {
        test: "test/integration/retry-after-error.test.ts :: step succeeds on retry when memoized with success data",
        quality: "strict",
      },
    ],
  },
  {
    id: "step.sleep",
    feature: "steps.sleep",
    kind: "integration",
    description: "Sleep and sleepUntil use async Sleep opcodes and resume from null memo",
    clauses: ["5.2-step-memo-timeout", "5.3.2-step-sleep"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/durable-sleep.test.ts :: returns 206 with Sleep opcode on first invocation",
        quality: "strict",
      },
      { test: "test/integration/durable-sleep.test.ts :: returns 200 after sleep completes", quality: "strict" },
      {
        test: "test/integration/durable-sleep.test.ts :: sleepUntil emits Sleep opcode with ISO timestamp",
        quality: "strict",
      },
      { test: "test/integration/durable-sleep.test.ts :: sleepUntil with unix timestamp", quality: "strict" },
      { test: "test/integration/durable-sleep.test.ts :: sleepUntil with ISO string", quality: "strict" },
      { test: "test/integration/durable-sleep.test.ts :: various Duration formats", quality: "strict" },
    ],
  },
  {
    id: "step.wait-for-event",
    feature: "steps.wait_for_event",
    kind: "integration",
    description: "WaitForEvent plans, resumes on event payload, and yields timeout on null",
    clauses: ["5.3.3-step-wait-for-event", "5.2-step-memo-timeout"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/wait-for-event.test.ts :: returns 206 with WaitForEvent opcode on first invocation",
        quality: "strict",
      },
      {
        test: "test/integration/wait-for-event.test.ts :: returns approved result when event received",
        quality: "strict",
      },
      {
        test: "test/integration/wait-for-event.test.ts :: returns timeout result when null received",
        quality: "strict",
      },
      { test: "test/integration/wait-for-event.test.ts :: waitForEvent without match expression", quality: "strict" },
      {
        test: "test/integration/wait-for-event.test.ts :: waitForEvent with various timeout durations",
        quality: "strict",
      },
      {
        test: "test/integration/regression.test.ts :: waitForEvent result has payload fields directly accessible",
        quality: "strict",
      },
      {
        test: "test/integration/regression.test.ts :: waitForEvent works when Inngest sends payload directly (not wrapped in event)",
        quality: "strict",
      },
      {
        test: "test/integration/regression.test.ts :: waitForEvent returns None when data is null (timeout)",
        quality: "strict",
      },
    ],
  },
  {
    id: "step.invoke",
    feature: "steps.invoke",
    kind: "integration",
    description: "InvokeFunction uses async opcode, composite function_id, and resumes from memoized data",
    clauses: ["5.3.4-step-invoke", "1.3.3-composite-id"],
    status: "covered",
    evidence: [
      { test: "test/integration/invoke-function.test.ts :: returns 206 with InvokeFunction opcode", quality: "strict" },
      {
        test: "test/integration/invoke-function.test.ts :: returns 200 with combined result when invoke completes",
        quality: "strict",
      },
      {
        test: "test/integration/invoke-function.test.ts :: verifies function_id format follows convention",
        quality: "strict",
      },
      {
        test: "test/integration/regression.test.ts :: invoke opcode has payload wrapped in { data } per Inngest protocol",
        quality: "strict",
      },
    ],
  },
  {
    id: "step.invoke-errors",
    feature: "steps.invoke",
    kind: "integration",
    description: "Invoke memoized errors propagate as function failures",
    clauses: ["5.2-step-memo-error", "5.3.4-step-invoke-error"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/step-error-handling.test.ts :: propagates error when invoked function result has error",
        quality: "strict",
      },
      {
        test: "test/integration/invoke-function.test.ts :: handles undefined result when step has no data",
        quality: "strict",
      },
    ],
  },
  {
    id: "step.send-event",
    feature: "steps.send_event",
    kind: "integration",
    description: "sendEvent is durable, replays from memoized ids, and targets the correct endpoint",
    clauses: ["5.3.5-step-send-event", "4.1.4-send-request-headers"],
    status: "partial",
    evidence: [
      { test: "test/integration/send-event.test.ts :: executes sendEvent step when memoized", quality: "strict" },
      { test: "test/integration/send-event.test.ts :: sendEvent emits correct StepRun opcode", quality: "strict" },
      { test: "test/integration/send-event.test.ts :: fails when event key not configured", quality: "strict" },
      {
        test: "test/integration/send-event.test.ts :: verifies event is sent to correct endpoint with eventKey during execution",
        quality: "partial",
      },
    ],
  },
  {
    id: "parallelism",
    feature: "parallelism",
    kind: "integration",
    description: "Parallel step planning and memoization work regardless of order",
    clauses: ["5.5-parallelism", "5.1.3-decide-when-to-report", "5.2-step-memo-data"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/parallel-steps.test.ts :: returns 206 with all parallel step opcodes on first invocation",
        quality: "strict",
      },
      {
        test: "test/integration/parallel-steps.test.ts :: returns 206 with remaining opcodes when partially memoized",
        quality: "strict",
      },
      {
        test: "test/integration/parallel-steps.test.ts :: returns 200 with final result when all steps memoized",
        quality: "strict",
      },
      { test: "test/integration/parallel-steps.test.ts :: handles memoization in any order", quality: "strict" },
      {
        test: "test/integration/parallel-steps.test.ts :: returns 206 with both Step and Sleep opcodes",
        quality: "strict",
      },
      {
        test: "test/integration/parallel-steps.test.ts :: completes when both step.run and step.sleep are memoized",
        quality: "strict",
      },
      {
        test: "test/integration/regression.test.ts :: parallel sleep + run: completion with null sleep result returns 200",
        quality: "strict",
      },
      {
        test: "test/integration/regression.test.ts :: target step executes even when disable_immediate_execution is true",
        quality: "strict",
      },
    ],
  },
  {
    id: "registration-options",
    feature: "registration",
    kind: "unit",
    description: "Function options serialize into registration payload for supported non-advanced features",
    clauses: [
      "4.3.2-register-retries",
      "4.3.2-register-cancel",
      "4.3.2-register-timeouts",
      "4.3.2-register-rate-limit",
      "4.3.2-register-throttle",
      "4.3.2-register-debounce",
      "4.3.2-register-concurrency",
      "4.3.2-register-priority",
      "4.3.2-register-singleton",
      "4.3.2-register-batch-events",
      "4.3.2-register-idempotency",
    ],
    status: "covered",
    evidence: [
      { test: "test/unit/function.test.ts :: serializes function with cancelOn", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes function with timeouts", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes rateLimit", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes throttle", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes debounce", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes concurrency as number", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes concurrency as object", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes concurrency as tuple", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes priority", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes singleton", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes batchEvents", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes idempotency", quality: "strict" },
    ],
  },
  {
    id: "client.send-event",
    feature: "client",
    kind: "unit",
    description: "Client sendEvent succeeds and fails without event key in cloud mode",
    clauses: ["1.3.4-event-shape", "3.1-event-key", "4.1.4-send-request-headers", "4.2.1-targeting"],
    status: "partial",
    evidence: [
      { test: "test/unit/client.test.ts :: sends events successfully", quality: "partial" },
      { test: "test/unit/client.test.ts :: fails without event key in cloud mode", quality: "strict" },
      { test: "test/unit/client.test.ts :: handles HTTP error in sendEvent", quality: "partial" },
    ],
  },
  {
    id: "checkpoint.config.serialization",
    feature: "checkpointing",
    kind: "unit",
    description: "Function with explicit checkpoint config serializes into registration payload",
    clauses: ["10.1.1-sync-payload"],
    status: "covered",
    evidence: [
      {
        test: "test/unit/checkpoint-config.test.ts :: serializes checkpoint config into registration payload",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.config.boolean-true",
    feature: "checkpointing",
    kind: "unit",
    description: "checkpointing: true expands to defaults (bufferedSteps=1, maxInterval=0s, maxRuntime=10s)",
    clauses: ["10.1-default-enabled", "10.1.1-sync-payload"],
    status: "covered",
    evidence: [
      {
        test: "test/unit/checkpoint-config.test.ts :: checkpointing true uses defaults",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.config.opt-out",
    feature: "checkpointing",
    kind: "unit",
    description: "checkpointing: false omits checkpoint block from registration",
    clauses: ["10.1-config-functionLevel"],
    status: "covered",
    evidence: [
      {
        test: "test/unit/checkpoint-config.test.ts :: checkpointing false omits registration block",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.config.client-level-default",
    feature: "checkpointing",
    kind: "unit",
    description: "Client-level checkpointing applies when function-level not set",
    clauses: ["10.1-config-clientLevel"],
    status: "covered",
    evidence: [
      {
        test: "test/unit/checkpoint-config.test.ts :: client-level checkpointing applies when function-level absent",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.config.function-overrides-client",
    feature: "checkpointing",
    kind: "unit",
    description: "Function-level checkpointing overrides client-level",
    clauses: ["10.1-config-functionLevel", "10.1-config-clientLevel"],
    status: "covered",
    evidence: [
      {
        test: "test/unit/checkpoint-config.test.ts :: function-level checkpointing overrides client",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.entry-conditions",
    feature: "checkpointing",
    kind: "integration",
    description: "Enters checkpoint mode iff fn_id present, no urlStepId, !disable_immediate_execution",
    clauses: ["10.4.1-bufferedSteps-flush"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: enters checkpoint mode under correct conditions",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.bufferedSteps-flush",
    feature: "checkpointing",
    kind: "integration",
    description: "bufferedSteps=2 with 3 step.runs flushes after step 2; final 206 contains [step3, RunComplete]",
    clauses: ["10.4.1-bufferedSteps-flush", "10.4.1-completion-runComplete"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: bufferedSteps=2 flushes after every two steps",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.bufferedSteps-1",
    feature: "checkpointing",
    kind: "integration",
    description: "Default bufferedSteps=1 flushes after every step",
    clauses: ["10.4.1-bufferedSteps-flush"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: default bufferedSteps=1 flushes after each step",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.maxInterval-flush",
    feature: "checkpointing",
    kind: "integration",
    description: "maxInterval triggers time-based flush before bufferedSteps reached",
    clauses: ["10.4.1-maxInterval-flush"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-maxRuntime.test.ts :: maxInterval triggers time-based flush",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.flush-on-async-opcode",
    feature: "checkpointing",
    kind: "integration",
    description: "Async opcode (sleep/wait/invoke) flushes buffer first, then yields 206 with the async opcode",
    clauses: ["10.2-async-flush-before-yield", "10.4.1-async-opcode-yield"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: flushes buffer before yielding on async opcode",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.flush-on-completion",
    feature: "checkpointing",
    kind: "integration",
    description: "Function returning a value yields 206 with [unflushed..., RunComplete(value)]",
    clauses: ["10.4.1-completion-runComplete"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: appends RunComplete on successful completion",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.flush-on-step-error",
    feature: "checkpointing",
    kind: "integration",
    description: "step.run throwing flushes buffered prior steps; 206 includes them before StepError opcode",
    clauses: ["10.4.3-graceful-fallback"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: includes buffered steps before StepError on failure",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.runComplete-shape",
    feature: "checkpointing",
    kind: "integration",
    description: "RunComplete opcode {op,id,data} carries the function return value",
    clauses: ["10.4.1-completion-runComplete"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: RunComplete carries function return value",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.api-payload-shape",
    feature: "checkpointing",
    kind: "integration",
    description: "Outbound POST body has {run_id, fn_id, qi_id, steps, ts}",
    clauses: ["10.3.1-async-payload-shape"],
    status: "covered",
    evidence: [
      {
        test: "test/unit/checkpoint-api.test.ts :: posts correct body shape to async endpoint",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.api-bearer-auth",
    feature: "checkpointing",
    kind: "integration",
    description: "Authorization: Bearer {hashed signing key} + SDK headers present on outbound POST",
    clauses: ["10.3.1-async-bearer-auth"],
    status: "covered",
    evidence: [
      {
        test: "test/unit/checkpoint-api.test.ts :: sends bearer auth and SDK headers",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.api-401-fallback",
    feature: "checkpointing",
    kind: "integration",
    description: "401 with primary signing key triggers retry with fallback; subsequent calls use fallback first",
    clauses: ["10.3.4-signing-key-fallback"],
    status: "covered",
    evidence: [
      {
        test: "test/unit/checkpoint-api.test.ts :: 401 triggers fallback signing key + Ref flip",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.api-retry-exponential",
    feature: "checkpointing",
    kind: "integration",
    description: "5xx responses retried up to 5 times with exponential backoff before falling back",
    clauses: ["10.3.3-retry-behavior"],
    status: "covered",
    evidence: [
      {
        test: "test/unit/checkpoint-api.test.ts :: retries 5xx responses with exponential backoff",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.graceful-fallback-on-failure",
    feature: "checkpointing",
    kind: "integration",
    description: "Persistent API failure causes 206 to include all buffered steps (no step loss)",
    clauses: ["10.4.3-graceful-fallback"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: includes buffered steps in 206 when API fails",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.maxRuntime-discovery",
    feature: "checkpointing",
    kind: "integration",
    description: "maxRuntime exceeded yields 206 ending in DiscoveryRequest opcode",
    clauses: ["10.4.1-maxRuntime-discoveryRequest"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-maxRuntime.test.ts :: emits DiscoveryRequest after maxRuntime",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.disabled",
    feature: "checkpointing",
    kind: "integration",
    description: "checkpointing: false at function level disables checkpoint mode entirely",
    clauses: ["10.1-config-functionLevel"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: function-level false disables checkpoint mode",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.urlStepId-disables",
    feature: "checkpointing",
    kind: "integration",
    description: "urlStepId set on Call Request bypasses checkpoint mode",
    clauses: ["10.4.1-bufferedSteps-flush"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: urlStepId disables checkpoint mode",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.disable-immediate-execution",
    feature: "checkpointing",
    kind: "integration",
    description: "ctx.disable_immediate_execution=true disables checkpoint mode",
    clauses: ["10.4.1-bufferedSteps-flush"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: disable_immediate_execution disables checkpoint mode",
        quality: "strict",
      },
    ],
  },
  {
    id: "checkpoint.async.only-stepRun-sent",
    feature: "checkpointing",
    kind: "integration",
    description: "Outbound checkpoint POST body contains only StepRun opcodes (no async opcodes)",
    clauses: ["10.2-only-stepRun-checkpointed"],
    status: "covered",
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: outbound body contains only StepRun opcodes",
        quality: "strict",
      },
    ],
  },
] as const;

export const clauses: ReadonlyArray<SpecClause> = [
  {
    id: "3.1-event-key",
    section: "3.1",
    title: "Support INNGEST_EVENT_KEY",
    level: "MUST",
    scope: "in-scope",
    feature: "env",
    status: "partial",
    text: "The SDK MUST support INNGEST_EVENT_KEY.",
    scenarios: ["env.layer-from-env.basic", "client.send-event"],
    evidence: [
      { test: "test/unit/client.test.ts :: layerFromEnv creates layer from environment", quality: "partial" },
      { test: "test/unit/client.test.ts :: fails without event key in cloud mode", quality: "strict" },
    ],
    missingCases: ["Auto-load event key into sendEvent path", "Verify cloud-mode event endpoint derived from env only"],
  },
  {
    id: "3.1-signing-key",
    section: "3.1",
    title: "Support INNGEST_SIGNING_KEY",
    level: "MUST",
    scope: "in-scope",
    feature: "env",
    status: "partial",
    text: "The SDK MUST support INNGEST_SIGNING_KEY.",
    scenarios: ["env.layer-from-env.basic", "signature.validation-matrix"],
    evidence: [
      { test: "test/unit/client.test.ts :: layerFromEnv creates layer from environment", quality: "partial" },
      { test: "test/unit/signature.test.ts :: production mode validation matrix", quality: "strict" },
    ],
    missingCases: ["HTTP handler exercised with env-derived signing key"],
  },
  {
    id: "3.1-signing-key-fallback",
    section: "3.1",
    title: "Support INNGEST_SIGNING_KEY_FALLBACK",
    level: "MUST",
    scope: "in-scope",
    feature: "env",
    status: "partial",
    text: "The SDK MUST attempt to use INNGEST_SIGNING_KEY_FALLBACK when the primary key fails.",
    scenarios: ["env.layer-from-env.basic", "signature.validation-matrix"],
    evidence: [
      { test: "test/unit/client.test.ts :: layerFromEnv creates layer from environment", quality: "partial" },
      {
        test: "test/unit/signature.test.ts :: succeeds when primary key fails but fallback matches",
        quality: "strict",
      },
    ],
    missingCases: ["Fallback key through actual HTTP request verification", "Fallback key on outbound API fetches"],
  },
  {
    id: "3.1-inngest-env",
    section: "3.1",
    title: "Use INNGEST_ENV for outbound X-Inngest-Env",
    level: "MUST",
    scope: "in-scope",
    feature: "env",
    status: "missing",
    text: "INNGEST_ENV MUST be used to set the X-Inngest-Env header when making requests to an Inngest Server.",
    scenarios: ["client.send-event"],
    evidence: [],
    missingCases: [
      "layerFromEnv loads INNGEST_ENV",
      "sendEvent forwards X-Inngest-Env from env config",
      "registration/fetch requests forward X-Inngest-Env if required",
    ],
    notes: "Client supports config.env but layerFromEnv does not read INNGEST_ENV and no test asserts the header.",
  },
  {
    id: "4.1.2-sdk-header",
    section: "4.1.2",
    title: "Call responses include X-Inngest-Sdk",
    level: "MUST",
    scope: "in-scope",
    feature: "headers",
    status: "covered",
    text: "When responding to a Call Request, the SDK MUST send X-Inngest-Sdk.",
    scenarios: ["call.simple-success", "introspection.basic"],
    evidence: [{ test: "test/integration/functiongroup-http.test.ts :: returns SDK headers", quality: "strict" }],
  },
  {
    id: "4.1.2-req-version",
    section: "4.1.2",
    title: "Call responses include X-Inngest-Req-Version: 2",
    level: "MUST",
    scope: "in-scope",
    feature: "headers",
    status: "failing",
    text: "When responding to a Call Request, the SDK MUST send X-Inngest-Req-Version and it MUST be 2.",
    scenarios: ["call.simple-success", "call.function-errors"],
    evidence: [],
    missingCases: [
      "Success response header assertion",
      "Error response header assertion",
      "206 response header assertion",
    ],
    notes: "src/internal/handler.ts and src/internal/driver.ts currently hardcode request version 1.",
  },
  {
    id: "4.1.3-dev-bypass",
    section: "4.1.3",
    title: "Dev mode bypasses signature verification",
    level: "SHOULD",
    scope: "in-scope",
    feature: "signature",
    status: "covered",
    text: "If targeting the Dev Server, the SDK SHOULD NOT attempt to verify the signature.",
    scenarios: ["signature.dev-bypass"],
    evidence: [{ test: "test/unit/signature.test.ts :: bypasses verification when isDev is true", quality: "strict" }],
  },
  {
    id: "4.1.3-missing-signing-key",
    section: "4.1.3",
    title: "Missing signing key rejects cloud request",
    level: "MUST",
    scope: "in-scope",
    feature: "signature",
    status: "partial",
    text: "If a signing key has not been provided, the SDK MUST reject the request with 500.",
    scenarios: ["signature.validation-matrix"],
    evidence: [{ test: "test/unit/signature.test.ts :: fails with missing signing key", quality: "strict" }],
    missingCases: ["HTTP handler returns 500, not just service failure"],
    notes: "Signature service is covered, but HTTP layer currently maps SignatureError to 401.",
  },
  {
    id: "4.1.3-missing-header",
    section: "4.1.3",
    title: "Missing signature header rejects cloud request",
    level: "MUST",
    scope: "in-scope",
    feature: "signature",
    status: "partial",
    text: "If targeting cloud and no X-Inngest-Signature header is provided, the SDK MUST reject with 500.",
    scenarios: ["signature.validation-matrix"],
    evidence: [{ test: "test/unit/signature.test.ts :: fails with missing signature header", quality: "strict" }],
    missingCases: ["HTTP handler returns 500 for missing header"],
    notes: "HTTP layer currently maps SignatureError to 401.",
  },
  {
    id: "4.1.3-expired-header",
    section: "4.1.3",
    title: "Expired signature rejects request",
    level: "MUST",
    scope: "in-scope",
    feature: "signature",
    status: "partial",
    text: "If the timestamp is outside the validity window, the SDK MUST reject the request with 500.",
    scenarios: ["signature.validation-matrix"],
    evidence: [
      { test: "test/unit/signature.test.ts :: fails with expired signature (> 5 minutes old)", quality: "strict" },
      { test: "test/unit/signature.test.ts :: fails with future signature (> 5 minutes ahead)", quality: "strict" },
    ],
    missingCases: ["HTTP handler returns 500 for expired signature"],
    notes: "HTTP layer currently maps SignatureError to 401.",
  },
  {
    id: "4.1.3-invalid-format",
    section: "4.1.3",
    title: "Malformed signature header rejects request",
    level: "MUST",
    scope: "in-scope",
    feature: "signature",
    status: "partial",
    text: "Malformed signature headers MUST be rejected.",
    scenarios: ["signature.validation-matrix"],
    evidence: [{ test: "test/unit/signature.test.ts :: fails with invalid signature format", quality: "strict" }],
    missingCases: ["HTTP handler returns 500 for malformed signature"],
    notes: "HTTP layer currently maps SignatureError to 401.",
  },
  {
    id: "4.1.3-invalid-signature",
    section: "4.1.3",
    title: "Invalid HMAC rejects request",
    level: "MUST",
    scope: "in-scope",
    feature: "signature",
    status: "partial",
    text: "If the generated hash does not match the signature, the SDK MUST reject with 500.",
    scenarios: ["signature.validation-matrix"],
    evidence: [
      { test: "test/unit/signature.test.ts :: fails with invalid signature (wrong key)", quality: "strict" },
      { test: "test/unit/signature.test.ts :: fails with invalid signature (tampered body)", quality: "strict" },
    ],
    missingCases: ["HTTP handler returns 500 for invalid hmac"],
    notes: "HTTP layer currently maps SignatureError to 401.",
  },
  {
    id: "4.1.4-send-request-headers",
    section: "4.1.4",
    title: "Outbound requests include SDK headers and auth",
    level: "MUST",
    scope: "in-scope",
    feature: "headers",
    status: "failing",
    text: "When sending any request to Inngest, the SDK MUST send X-Inngest-Sdk, X-Inngest-Req-Version, and Authorization: Bearer <hashed signing key>.",
    scenarios: ["sync.registration-core", "step.send-event", "client.send-event"],
    evidence: [
      {
        test: "test/integration/registration.test.ts :: PUT / triggers registration POST to Inngest",
        quality: "partial",
        notes: "Payload covered, headers not asserted",
      },
      {
        test: "test/integration/send-event.test.ts :: verifies event is sent to correct endpoint with eventKey during execution",
        quality: "partial",
        notes: "Endpoint covered, headers not asserted",
      },
    ],
    missingCases: [
      "Assert X-Inngest-Sdk on registration",
      "Assert X-Inngest-Req-Version on registration",
      "Assert hashed bearer auth on registration",
      "Assert sendEvent outbound headers",
    ],
    notes:
      "Registration currently sends raw signing key; sendEvent uses effect-ts:v2.0.0 and omits request version and bearer auth.",
  },
  {
    id: "4.2.1-targeting",
    section: "4.2.1",
    title: "Default targeting and dev override",
    level: "MUST",
    scope: "in-scope",
    feature: "targeting",
    status: "partial",
    text: "The SDK MUST default cloud targets correctly and use INNGEST_DEV to target the dev server.",
    scenarios: ["client.send-event"],
    evidence: [{ test: "test/unit/client.test.ts :: fails without event key in cloud mode", quality: "partial" }],
    missingCases: [
      "Assert default cloud API/event URLs",
      "Assert INNGEST_DEV toggles dev defaults",
      "Assert custom INNGEST_DEV origin",
    ],
    notes: "Current client defaults to dev mode unless explicitly set; layerFromEnv does not read INNGEST_DEV.",
  },
  {
    id: "4.2.2-dev-disables-verification",
    section: "4.2.2",
    title: "INNGEST_DEV disables verification",
    level: "MUST",
    scope: "in-scope",
    feature: "targeting",
    status: "partial",
    text: "Presence of INNGEST_DEV or equivalent MUST turn off signature verification.",
    scenarios: ["signature.dev-bypass"],
    evidence: [{ test: "test/unit/signature.test.ts :: bypasses verification when isDev is true", quality: "strict" }],
    missingCases: ["Environment-driven dev mode test through layerFromEnv/HTTP handler"],
  },
  {
    id: "4.3.1-sync-response-shape",
    section: "4.3.1",
    title: "PUT sync responds with { message, modified }",
    level: "MUST",
    scope: "in-scope",
    feature: "sync",
    status: "failing",
    text: "A sync response MUST use the JSON shape { message: string; modified: boolean }.",
    scenarios: ["sync.registration-core", "sync.registration-failure"],
    evidence: [
      {
        test: "test/integration/registration.test.ts :: PUT / triggers registration POST to Inngest",
        quality: "partial",
      },
    ],
    missingCases: ["Assert modified present on success", "Assert modified=false on failure"],
    notes: "RegisterResponse schema currently only includes message and drops modified.",
  },
  {
    id: "4.3.2-register-post",
    section: "4.3.2",
    title: "PUT triggers POST /fn/register",
    level: "MUST",
    scope: "in-scope",
    feature: "sync",
    status: "covered",
    text: "Following a sync request, the SDK MUST send a POST request to /fn/register.",
    scenarios: ["sync.registration-core"],
    evidence: [
      {
        test: "test/integration/registration.test.ts :: PUT / triggers registration POST to Inngest",
        quality: "strict",
      },
    ],
  },
  {
    id: "4.3.2-register-payload",
    section: "4.3.2",
    title: "Registration payload contains required fields",
    level: "MUST",
    scope: "in-scope",
    feature: "sync",
    status: "covered",
    text: "The registration payload MUST contain url, deployType, appName, sdk, v, and functions with valid step runtime URLs.",
    scenarios: ["sync.registration-core", "registration-options"],
    evidence: [
      {
        test: "test/integration/registration.test.ts :: PUT / triggers registration POST to Inngest",
        quality: "strict",
      },
      {
        test: "test/integration/registration.test.ts :: step URL includes fnId and stepId query parameters",
        quality: "strict",
      },
      { test: "test/unit/function.test.ts :: toRegistration coverage", quality: "strict" },
    ],
  },
  {
    id: "4.3.2-step-runtime-url",
    section: "4.3.2",
    title: "Registration step runtime URL includes fnId and stepId",
    level: "MUST",
    scope: "in-scope",
    feature: "sync",
    status: "covered",
    text: "The runtime url MUST include stepId=step and fnId=<function-id>.",
    scenarios: ["sync.registration-core"],
    evidence: [
      {
        test: "test/integration/registration.test.ts :: step URL includes fnId and stepId query parameters",
        quality: "strict",
      },
    ],
  },
  {
    id: "4.3.2-deployid-forwarding",
    section: "4.3.2",
    title: "deployId is forwarded to /fn/register and omitted from payload url",
    level: "MUST",
    scope: "in-scope",
    feature: "sync",
    status: "missing",
    text: "If deployId is set on the incoming sync request, the SDK MUST forward it to /fn/register and MUST NOT include it in the payload url.",
    scenarios: [],
    evidence: [],
    missingCases: [
      "Incoming PUT with deployId",
      "Assert outbound query string includes deployId",
      "Assert payload url omits deployId",
    ],
  },
  {
    id: "4.3.2-expected-server-kind",
    section: "4.3.2",
    title: "Forward X-Inngest-Server-Kind as X-Inngest-Expected-Server-Kind",
    level: "SHOULD",
    scope: "in-scope",
    feature: "sync",
    status: "missing",
    text: "If X-Inngest-Server-Kind is set on the inbound sync request, the SDK SHOULD forward it as X-Inngest-Expected-Server-Kind.",
    scenarios: [],
    evidence: [],
    missingCases: ["Assert inbound header forwarding during sync"],
  },
  {
    id: "4.3.3-sync-failure",
    section: "4.3.3",
    title: "Sync failure returns 500 and modified false",
    level: "SHOULD",
    scope: "in-scope",
    feature: "sync",
    status: "failing",
    text: "An SDK SHOULD return 500 Internal Server Error with { message, modified: false } when registration fails.",
    scenarios: ["sync.registration-failure"],
    evidence: [
      { test: "test/integration/registration.test.ts :: handles registration failure gracefully", quality: "partial" },
    ],
    missingCases: ["Assert HTTP status 500 on failed register", "Assert modified=false"],
    notes: "handleRegistration currently catches failures and still returns status 200.",
  },
  {
    id: "4.3.4-sync-success-modified",
    section: "4.3.4",
    title: "Sync success returns modified passthrough",
    level: "MUST",
    scope: "in-scope",
    feature: "sync",
    status: "failing",
    text: "The SDK MUST respond with the modified value returned by Inngest, or false if omitted.",
    scenarios: ["sync.registration-core"],
    evidence: [
      {
        test: "test/integration/registration.test.ts :: PUT / triggers registration POST to Inngest",
        quality: "partial",
      },
    ],
    missingCases: ["Assert modified=true passthrough", "Assert default modified=false when omitted"],
    notes: "RegisterResponse schema drops modified entirely.",
  },
  {
    id: "4.4.1-missing-fnid",
    section: "4.4.1",
    title: "Missing fnId query parameter is rejected",
    level: "MUST",
    scope: "in-scope",
    feature: "call",
    status: "partial",
    text: "The SDK MUST use fnId to find the correct Function to call; invalid query input must be rejected.",
    scenarios: ["call.query-errors"],
    evidence: [
      { test: "test/integration/functiongroup-http.test.ts :: returns error when fnId is missing", quality: "partial" },
    ],
    missingCases: ["Assert exact status and body shape", "Assert no-retry header"],
    notes: "Test currently allows multiple statuses instead of the exact contract.",
  },
  {
    id: "4.4.1-unknown-function",
    section: "4.4.1",
    title: "Unknown function returns 500",
    level: "MUST",
    scope: "in-scope",
    feature: "call",
    status: "failing",
    text: "If the function cannot be found, the SDK MUST return 500 Internal Server Error.",
    scenarios: ["call.query-errors"],
    evidence: [
      {
        test: "test/integration/functiongroup-http.test.ts :: returns error when function not found",
        quality: "partial",
      },
    ],
    missingCases: ["Assert exact 500 status", "Assert body shape per spec"],
    notes: "handleExecution currently returns 404 FunctionNotFoundError.",
  },
  {
    id: "4.4.1-invalid-json",
    section: "4.4.1",
    title: "Malformed JSON is rejected",
    level: "MUST",
    scope: "in-scope",
    feature: "call",
    status: "partial",
    text: "Malformed execution payloads must be rejected.",
    scenarios: ["call.invalid-body"],
    evidence: [
      { test: "test/integration/functiongroup-http.test.ts :: returns 500 for invalid JSON body", quality: "partial" },
    ],
    missingCases: ["Cloud-mode signed malformed request through handler"],
  },
  {
    id: "4.4.1-invalid-body-schema",
    section: "4.4.1",
    title: "Invalid body schema is rejected",
    level: "MUST",
    scope: "in-scope",
    feature: "call",
    status: "partial",
    text: "Invalid execution payloads must be rejected.",
    scenarios: ["call.invalid-body"],
    evidence: [
      {
        test: "test/integration/functiongroup-http.test.ts :: returns 500 for invalid request body schema",
        quality: "partial",
      },
    ],
    missingCases: ["Exact error body contract", "Cloud-mode signed invalid schema request"],
  },
  {
    id: "4.4.1-stepid-routing",
    section: "4.4.1",
    title: "URL stepId selects the specific step",
    level: "MUST",
    scope: "in-scope",
    feature: "call",
    status: "covered",
    text: "The SDK MUST respect the stepId query parameter when executing a specific step.",
    scenarios: ["call.stepid-precedence"],
    evidence: [
      { test: "test/integration/functiongroup-http.test.ts :: parses stepId from query params", quality: "strict" },
      {
        test: "test/integration/regression.test.ts :: specific stepId in URL causes that step to execute",
        quality: "strict",
      },
    ],
  },
  {
    id: "4.4.2-use-api-batch",
    section: "4.4.2",
    title: "ctx.use_api fetches full batch payload",
    level: "MUST",
    scope: "in-scope",
    feature: "use_api",
    status: "missing",
    text: "When ctx.use_api is true, the SDK MUST GET /v0/runs/:run_id/batch and use those events.",
    scenarios: ["use-api.protocol-only"],
    evidence: [],
    missingCases: [
      "Fetch events from API",
      "Replace request.events with fetched batch",
      "Set event to first fetched event",
    ],
  },
  {
    id: "4.4.2-use-api-actions",
    section: "4.4.2",
    title: "ctx.use_api fetches memoized step data",
    level: "MUST",
    scope: "in-scope",
    feature: "use_api",
    status: "missing",
    text: "When ctx.use_api is true, the SDK MUST GET /v0/runs/:run_id/actions and use that step data.",
    scenarios: ["use-api.protocol-only"],
    evidence: [],
    missingCases: ["Fetch actions from API", "Use fetched steps as authoritative memo state"],
  },
  {
    id: "4.4.2-use-api-failure",
    section: "4.4.2",
    title: "ctx.use_api failures return 500",
    level: "MUST",
    scope: "in-scope",
    feature: "use_api",
    status: "missing",
    text: "If either use_api fetch fails or returns non-200, the SDK MUST return 500.",
    scenarios: ["use-api.protocol-only"],
    evidence: [],
    missingCases: ["Batch fetch non-200", "Actions fetch non-200", "Malformed fetched body"],
  },
  {
    id: "4.4.3-call-context",
    section: "4.4.3",
    title: "Handler receives event, events, runId, attempt, and step tools",
    level: "SHOULD",
    scope: "in-scope",
    feature: "call",
    status: "covered",
    text: "The SDK SHOULD provide event, events, runId, attempt, and step tooling to handler code.",
    scenarios: ["call.simple-success"],
    evidence: [
      {
        test: "test/integration/regression.test.ts :: handler receives array when events.length > 1",
        quality: "strict",
      },
    ],
  },
  {
    id: "4.4.3-call-success",
    section: "4.4.3",
    title: "Successful function returns 200 JSON",
    level: "MUST",
    scope: "in-scope",
    feature: "call",
    status: "covered",
    text: "A successful function response MUST return 200 OK with the returned value as JSON.",
    scenarios: ["call.simple-success"],
    evidence: [
      {
        test: "test/integration/hello-world.test.ts :: executes function and returns 200 with result",
        quality: "strict",
      },
    ],
  },
  {
    id: "4.4.3-error-shape",
    section: "4.4.3",
    title: "Function errors use {name,message,stack?} payload",
    level: "MUST",
    scope: "in-scope",
    feature: "call",
    status: "failing",
    text: "If the function throws, the SDK MUST respond with { name, message, stack? }.",
    scenarios: ["call.function-errors"],
    evidence: [
      {
        test: "test/integration/retry-after-error.test.ts :: returns 500 with Retry-After header for function-level retry",
        quality: "partial",
      },
    ],
    missingCases: ["Retriable error root payload", "Non-retriable error root payload"],
    notes: "Driver currently wraps function errors in { error: { ... } } instead of returning the root shape.",
  },
  {
    id: "4.4.3-retriable-error",
    section: "4.4.3",
    title: "Retriable function errors return 500 and X-Inngest-No-Retry:false",
    level: "MUST",
    scope: "in-scope",
    feature: "call",
    status: "covered",
    text: "Retriable function errors MUST return 500 with X-Inngest-No-Retry: false.",
    scenarios: ["call.function-errors"],
    evidence: [
      {
        test: "test/integration/retry-after-error.test.ts :: returns 500 with Retry-After header for function-level retry",
        quality: "strict",
      },
      {
        test: "test/integration/step-error-handling.test.ts :: catches unexpected defects and returns 500",
        quality: "strict",
      },
    ],
  },
  {
    id: "4.4.3-nonretriable-error",
    section: "4.4.3",
    title: "Non-retriable function errors return 400 and X-Inngest-No-Retry:true",
    level: "MUST",
    scope: "in-scope",
    feature: "call",
    status: "failing",
    text: "Non-retriable function errors MUST return 400 with X-Inngest-No-Retry: true.",
    scenarios: ["call.function-errors"],
    evidence: [
      {
        test: "test/integration/regression.test.ts :: handler throwing NonRetriableError directly sets X-Inngest-No-Retry: true",
        quality: "partial",
      },
    ],
    missingCases: ["Exact 400 status assertion", "Exact root error payload assertion"],
    notes: "Driver currently returns 500 for NonRetriableError and only sets the no-retry header.",
  },
  {
    id: "4.4.3-retry-after",
    section: "4.4.3",
    title: "Retry-After is supported and implies retry",
    level: "MAY",
    scope: "in-scope",
    feature: "call",
    status: "covered",
    text: "If Retry-After is set, the SDK MUST also set X-Inngest-No-Retry: false.",
    scenarios: ["call.function-errors", "step.run-retry-after"],
    evidence: [
      {
        test: "test/integration/retry-after-error.test.ts :: emits StepError opcode (206) - NOT function-level retry",
        quality: "strict",
      },
      {
        test: "test/integration/retry-after-error.test.ts :: returns 500 with Retry-After header for function-level retry",
        quality: "strict",
      },
    ],
  },
  {
    id: "4.5-introspection-base",
    section: "4.5",
    title: "Introspection returns base schema",
    level: "MUST",
    scope: "in-scope",
    feature: "introspection",
    status: "covered",
    text: "An SDK MUST respond to an introspection request with a versioned schema.",
    scenarios: ["introspection.basic"],
    evidence: [
      {
        test: "test/integration/functiongroup-http.test.ts :: returns introspection response with function count",
        quality: "strict",
      },
      {
        test: "test/integration/introspection.test.ts :: introspection response includes correct schema_version",
        quality: "strict",
      },
    ],
  },
  {
    id: "4.5-introspection-dev-functions",
    section: "4.5",
    title: "Dev introspection can expose functions",
    level: "MUST",
    scope: "in-scope",
    feature: "introspection",
    status: "failing",
    text: "Response schemas MUST be versioned; supported privileged fields should appear when appropriate.",
    scenarios: ["introspection-auth-and-functions"],
    evidence: [
      {
        test: "test/integration/introspection.test.ts :: GET / in dev mode returns functions array",
        quality: "partial",
      },
    ],
    missingCases: ["Assert dev functions array contents"],
    notes: "Test documents expected behavior but current implementation does not include functions.",
  },
  {
    id: "4.5-introspection-authenticated",
    section: "4.5",
    title: "Authenticated introspection returns privileged fields",
    level: "MUST",
    scope: "in-scope",
    feature: "introspection",
    status: "missing",
    text: "Authenticated introspection responses should use the authenticated schema variant.",
    scenarios: ["introspection-auth-and-functions"],
    evidence: [],
    missingCases: [
      "Valid signed GET returns authentication_succeeded=true",
      "Assert app_id, api_origin, event_api_origin, hashes, framework, sdk fields",
    ],
  },
  {
    id: "5.1-step-response-shape",
    section: "5.1",
    title: "Step planning responses use opcode arrays",
    level: "MUST",
    scope: "in-scope",
    feature: "steps",
    status: "covered",
    text: "Step discovery responses MUST use the expected opcode array shape.",
    scenarios: ["step.run.discovery-and-replay", "step.sleep", "step.wait-for-event", "step.invoke", "parallelism"],
    evidence: [
      {
        test: "test/integration/step-memoization.test.ts :: returns 206 with StepPlanned on first invocation",
        quality: "strict",
      },
      {
        test: "test/integration/durable-sleep.test.ts :: returns 206 with Sleep opcode on first invocation",
        quality: "strict",
      },
      {
        test: "test/integration/wait-for-event.test.ts :: returns 206 with WaitForEvent opcode on first invocation",
        quality: "strict",
      },
      { test: "test/integration/invoke-function.test.ts :: returns 206 with InvokeFunction opcode", quality: "strict" },
      {
        test: "test/integration/parallel-steps.test.ts :: returns 206 with all parallel step opcodes on first invocation",
        quality: "strict",
      },
    ],
  },
  {
    id: "5.1.2-step-id-hashing",
    section: "5.1.2",
    title: "Step ids are SHA-1 hashes and repeats use suffixing",
    level: "MUST",
    scope: "in-scope",
    feature: "steps",
    status: "partial",
    text: "Step ids should be hashed deterministically; repeated ids should hash id:1, id:2, etc.",
    scenarios: ["step.run.discovery-and-replay", "parallelism"],
    evidence: [
      {
        test: "test/integration/step-memoization.test.ts :: returns 206 with StepPlanned on first invocation",
        quality: "strict",
      },
      { test: "test/integration/send-event.test.ts :: sendEvent emits correct StepRun opcode", quality: "strict" },
    ],
    missingCases: ["Duplicate user step ids in one handler", "Explicit repeat-index hash assertions"],
  },
  {
    id: "5.1.3-decide-when-to-report",
    section: "5.1.3",
    title: "Memoized steps are not re-reported",
    level: "MUST",
    scope: "in-scope",
    feature: "steps",
    status: "covered",
    text: "Already memoized steps should not be reported again.",
    scenarios: ["step.run.discovery-and-replay", "parallelism"],
    evidence: [
      {
        test: "test/integration/step-memoization.test.ts :: returns 200 with final result when step is memoized",
        quality: "strict",
      },
      {
        test: "test/integration/parallel-steps.test.ts :: returns 206 with remaining opcodes when partially memoized",
        quality: "strict",
      },
    ],
  },
  {
    id: "5.2-step-memo-data",
    section: "5.2",
    title: "Memoized data resumes prior steps",
    level: "MUST",
    scope: "in-scope",
    feature: "memoization",
    status: "covered",
    text: "Memoized data should resume and complete prior steps without rerunning user code.",
    scenarios: ["step.run.discovery-and-replay", "step.invoke", "step.send-event", "parallelism"],
    evidence: [
      {
        test: "test/integration/step-memoization.test.ts :: returns 200 with final result when step is memoized",
        quality: "strict",
      },
      {
        test: "test/integration/invoke-function.test.ts :: returns 200 with combined result when invoke completes",
        quality: "strict",
      },
      { test: "test/integration/send-event.test.ts :: executes sendEvent step when memoized", quality: "strict" },
      {
        test: "test/integration/parallel-steps.test.ts :: returns 200 with final result when all steps memoized",
        quality: "strict",
      },
    ],
  },
  {
    id: "5.2-step-memo-error",
    section: "5.2",
    title: "Memoized errors resume as failures",
    level: "MUST",
    scope: "in-scope",
    feature: "memoization",
    status: "covered",
    text: "Memoized step errors should resume as failures without rerunning the step.",
    scenarios: ["step.run.errors", "step.invoke-errors"],
    evidence: [
      {
        test: "test/integration/step-error-handling.test.ts :: re-raises error when memoized data has error property",
        quality: "strict",
      },
      {
        test: "test/integration/step-error-handling.test.ts :: propagates error when invoked function result has error",
        quality: "strict",
      },
    ],
  },
  {
    id: "5.2-step-memo-timeout",
    section: "5.2",
    title: "Null memo values behave like timeout/none",
    level: "MUST",
    scope: "in-scope",
    feature: "memoization",
    status: "covered",
    text: "Timeout-like memo values should resume correctly for sleep and waitForEvent.",
    scenarios: ["step.sleep", "step.wait-for-event", "parallelism"],
    evidence: [
      { test: "test/integration/durable-sleep.test.ts :: returns 200 after sleep completes", quality: "strict" },
      {
        test: "test/integration/wait-for-event.test.ts :: returns timeout result when null received",
        quality: "strict",
      },
      {
        test: "test/integration/regression.test.ts :: parallel sleep + run: completion with null sleep result returns 200",
        quality: "strict",
      },
    ],
  },
  {
    id: "5.3.1-step-run",
    section: "5.3.1",
    title: "step.run supports discovery, execution, and replay",
    level: "MUST",
    scope: "in-scope",
    feature: "steps.run",
    status: "covered",
    text: "step.run should discover work, execute targeted work, and replay memoized results.",
    scenarios: ["step.run.discovery-and-replay", "step.run.errors", "parallelism"],
    evidence: [
      {
        test: "test/integration/step-memoization.test.ts :: returns 206 with StepPlanned on first invocation",
        quality: "strict",
      },
      {
        test: "test/integration/regression.test.ts :: specific stepId in URL causes that step to execute",
        quality: "strict",
      },
    ],
  },
  {
    id: "5.3.2-step-sleep",
    section: "5.3.2",
    title: "Sleep and sleepUntil emit async Sleep opcodes",
    level: "MUST",
    scope: "in-scope",
    feature: "steps.sleep",
    status: "covered",
    text: "Sleep steps should emit async Sleep opcodes and resume from memoized null.",
    scenarios: ["step.sleep"],
    evidence: [
      {
        test: "test/integration/durable-sleep.test.ts :: returns 206 with Sleep opcode on first invocation",
        quality: "strict",
      },
      {
        test: "test/integration/durable-sleep.test.ts :: sleepUntil emits Sleep opcode with ISO timestamp",
        quality: "strict",
      },
    ],
  },
  {
    id: "5.3.3-step-wait-for-event",
    section: "5.3.3",
    title: "WaitForEvent emits async opcode and returns payload or timeout",
    level: "MUST",
    scope: "in-scope",
    feature: "steps.wait_for_event",
    status: "covered",
    text: "waitForEvent should emit an async WaitForEvent opcode, return event payloads, and yield none on timeout.",
    scenarios: ["step.wait-for-event"],
    evidence: [
      {
        test: "test/integration/wait-for-event.test.ts :: returns 206 with WaitForEvent opcode on first invocation",
        quality: "strict",
      },
      {
        test: "test/integration/wait-for-event.test.ts :: returns approved result when event received",
        quality: "strict",
      },
      {
        test: "test/integration/wait-for-event.test.ts :: returns timeout result when null received",
        quality: "strict",
      },
    ],
  },
  {
    id: "5.3.4-step-invoke",
    section: "5.3.4",
    title: "Invoke uses composite function id and payload",
    level: "MUST",
    scope: "in-scope",
    feature: "steps.invoke",
    status: "covered",
    text: "Invoke steps should emit async InvokeFunction opcodes with composite function ids and replay memoized results.",
    scenarios: ["step.invoke", "step.invoke-errors"],
    evidence: [
      { test: "test/integration/invoke-function.test.ts :: returns 206 with InvokeFunction opcode", quality: "strict" },
      {
        test: "test/integration/invoke-function.test.ts :: returns 200 with combined result when invoke completes",
        quality: "strict",
      },
      {
        test: "test/integration/invoke-function.test.ts :: verifies function_id format follows convention",
        quality: "strict",
      },
    ],
  },
  {
    id: "5.3.5-step-send-event",
    section: "5.3.5",
    title: "sendEvent is durable and replays ids",
    level: "MUST",
    scope: "in-scope",
    feature: "steps.send_event",
    status: "partial",
    text: "sendEvent should behave as a durable step and replay the ids returned from event ingestion.",
    scenarios: ["step.send-event"],
    evidence: [
      { test: "test/integration/send-event.test.ts :: executes sendEvent step when memoized", quality: "strict" },
      { test: "test/integration/send-event.test.ts :: sendEvent emits correct StepRun opcode", quality: "strict" },
    ],
    missingCases: [
      "Exact outbound headers and request version",
      "Cloud-mode hashed auth on event ingestion if required by spec",
    ],
  },
  {
    id: "5.4-recovery-and-stack",
    section: "5.4",
    title: "Recovery uses stack ordering when code changes",
    level: "MUST",
    scope: "in-scope",
    feature: "recovery",
    status: "missing",
    text: "Recovery should honor ctx.stack and recover deterministically when code changes.",
    scenarios: [],
    evidence: [],
    missingCases: ["ctx.stack re-entry ordering", "Code drift between attempts", "Earliest matching step recovery"],
    notes:
      "No dedicated tests and current step/driver code does not appear to consult stack ordering during discovery.",
  },
  {
    id: "5.5-parallelism",
    section: "5.5",
    title: "Parallel steps plan and replay deterministically",
    level: "MUST",
    scope: "in-scope",
    feature: "parallelism",
    status: "covered",
    text: "Parallel steps should be discoverable and resumable without depending on memo order.",
    scenarios: ["parallelism"],
    evidence: [
      {
        test: "test/integration/parallel-steps.test.ts :: returns 206 with all parallel step opcodes on first invocation",
        quality: "strict",
      },
      { test: "test/integration/parallel-steps.test.ts :: handles memoization in any order", quality: "strict" },
    ],
  },
  {
    id: "4.3.2-register-retries",
    section: "4.3.2",
    title: "Registration serializes retries",
    level: "MUST",
    scope: "in-scope",
    feature: "registration",
    status: "covered",
    text: "Supported retry options must serialize into the registration payload.",
    scenarios: ["sync.registration-core", "registration-options"],
    evidence: [
      {
        test: "test/integration/registration.test.ts :: PUT / triggers registration POST to Inngest",
        quality: "strict",
      },
    ],
  },
  {
    id: "4.3.2-register-cancel",
    section: "4.3.2",
    title: "Registration serializes cancel",
    level: "MUST",
    scope: "in-scope",
    feature: "registration",
    status: "covered",
    text: "Supported cancel options must serialize into the registration payload.",
    scenarios: ["registration-options"],
    evidence: [{ test: "test/unit/function.test.ts :: serializes function with cancelOn", quality: "strict" }],
  },
  {
    id: "4.3.2-register-timeouts",
    section: "4.3.2",
    title: "Registration serializes timeouts",
    level: "MUST",
    scope: "in-scope",
    feature: "registration",
    status: "covered",
    text: "Supported timeout options must serialize into the registration payload.",
    scenarios: ["registration-options"],
    evidence: [{ test: "test/unit/function.test.ts :: serializes function with timeouts", quality: "strict" }],
  },
  {
    id: "4.3.2-register-rate-limit",
    section: "4.3.2",
    title: "Registration serializes rateLimit",
    level: "MUST",
    scope: "in-scope",
    feature: "registration",
    status: "covered",
    text: "Supported rateLimit options must serialize into the registration payload.",
    scenarios: ["registration-options"],
    evidence: [{ test: "test/unit/function.test.ts :: serializes rateLimit", quality: "strict" }],
  },
  {
    id: "4.3.2-register-throttle",
    section: "4.3.2",
    title: "Registration serializes throttle",
    level: "MUST",
    scope: "in-scope",
    feature: "registration",
    status: "covered",
    text: "Supported throttle options must serialize into the registration payload.",
    scenarios: ["registration-options"],
    evidence: [{ test: "test/unit/function.test.ts :: serializes throttle", quality: "strict" }],
  },
  {
    id: "4.3.2-register-debounce",
    section: "4.3.2",
    title: "Registration serializes debounce",
    level: "MUST",
    scope: "in-scope",
    feature: "registration",
    status: "covered",
    text: "Supported debounce options must serialize into the registration payload.",
    scenarios: ["registration-options"],
    evidence: [{ test: "test/unit/function.test.ts :: serializes debounce", quality: "strict" }],
  },
  {
    id: "4.3.2-register-concurrency",
    section: "4.3.2",
    title: "Registration serializes concurrency",
    level: "MUST",
    scope: "in-scope",
    feature: "registration",
    status: "covered",
    text: "Supported concurrency options must serialize into the registration payload.",
    scenarios: ["registration-options"],
    evidence: [
      { test: "test/unit/function.test.ts :: serializes concurrency as number", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes concurrency as object", quality: "strict" },
      { test: "test/unit/function.test.ts :: serializes concurrency as tuple", quality: "strict" },
    ],
  },
  {
    id: "4.3.2-register-priority",
    section: "4.3.2",
    title: "Registration serializes priority",
    level: "MUST",
    scope: "in-scope",
    feature: "registration",
    status: "covered",
    text: "Supported priority options must serialize into the registration payload.",
    scenarios: ["registration-options"],
    evidence: [{ test: "test/unit/function.test.ts :: serializes priority", quality: "strict" }],
  },
  {
    id: "4.3.2-register-singleton",
    section: "4.3.2",
    title: "Registration serializes singleton",
    level: "MUST",
    scope: "in-scope",
    feature: "registration",
    status: "covered",
    text: "Supported singleton options must serialize into the registration payload.",
    scenarios: ["registration-options"],
    evidence: [{ test: "test/unit/function.test.ts :: serializes singleton", quality: "strict" }],
  },
  {
    id: "4.3.2-register-batch-events",
    section: "4.3.2",
    title: "Registration serializes batchEvents",
    level: "MUST",
    scope: "in-scope",
    feature: "registration",
    status: "covered",
    text: "Supported batchEvents options must serialize into the registration payload.",
    scenarios: ["registration-options"],
    evidence: [{ test: "test/unit/function.test.ts :: serializes batchEvents", quality: "strict" }],
  },
  {
    id: "4.3.2-register-idempotency",
    section: "4.3.2",
    title: "Registration serializes idempotency",
    level: "MUST",
    scope: "in-scope",
    feature: "registration",
    status: "covered",
    text: "Supported idempotency options must serialize into the registration payload.",
    scenarios: ["registration-options"],
    evidence: [{ test: "test/unit/function.test.ts :: serializes idempotency", quality: "strict" }],
  },
  {
    id: "10.1-config-clientLevel",
    section: "10.1",
    title: "Checkpointing supports client-level configuration",
    level: "SHOULD",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "An SDK SHOULD allow checkpoint configuration at the client level (default for all functions).",
    scenarios: ["checkpoint.config.client-level-default", "checkpoint.config.function-overrides-client"],
    evidence: [
      {
        test: "test/unit/checkpoint-config.test.ts :: client-level checkpointing applies when function-level absent",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.1-config-functionLevel",
    section: "10.1",
    title: "Checkpointing supports per-function configuration",
    level: "SHOULD",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "An SDK SHOULD allow checkpoint configuration at the function level (overrides client default).",
    scenarios: [
      "checkpoint.config.opt-out",
      "checkpoint.config.function-overrides-client",
      "checkpoint.async.disabled",
    ],
    evidence: [
      {
        test: "test/unit/checkpoint-config.test.ts :: function-level checkpointing overrides client",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.1-default-enabled",
    section: "10.1",
    title: "SDK MAY enable checkpointing by default",
    level: "MAY",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "If no explicit configuration is provided, the SDK MAY enable checkpointing by default.",
    scenarios: ["checkpoint.config.boolean-true"],
    evidence: [
      {
        test: "test/unit/checkpoint-config.test.ts :: checkpointing true uses defaults",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.1.1-sync-payload",
    section: "10.1.1",
    title: "Checkpoint config included in sync payload",
    level: "SHOULD",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "When registering a function with checkpointing enabled, the SDK SHOULD include the checkpoint configuration ({batch_steps, batch_interval, max_runtime}) in the sync payload.",
    scenarios: ["checkpoint.config.serialization", "checkpoint.config.boolean-true"],
    evidence: [
      {
        test: "test/integration/registration.test.ts :: registration includes checkpoint block when enabled",
        quality: "strict",
      },
      {
        test: "test/unit/checkpoint-config.test.ts :: serializes checkpoint config into registration payload",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.2-async-flush-before-yield",
    section: "10.2",
    title: "Async opcodes MUST cause flush + yield",
    level: "MUST",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "When the SDK is in checkpoint mode and encounters an async opcode (Sleep, WaitForEvent, InvokeFunction, etc.), it MUST stop checkpointing, flush buffered sync ops, and yield via the standard 206 response.",
    scenarios: ["checkpoint.async.flush-on-async-opcode"],
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: flushes buffer before yielding on async opcode",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.2-only-stepRun-checkpointed",
    section: "10.2",
    title: "Only sync opcodes (StepRun) sent to async checkpoint endpoint",
    level: "MUST",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "Only sync opcodes (StepRun) are accepted by the async checkpoint endpoint. Async opcodes MUST NOT be sent.",
    scenarios: ["checkpoint.async.only-stepRun-sent"],
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: outbound body contains only StepRun opcodes",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.3.1-async-endpoint",
    section: "10.3.1",
    title: "Async checkpoint POSTs to /v1/checkpoint/{runID}/async",
    level: "MUST",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "Async checkpointing MUST POST to {apiBaseURL}/v1/checkpoint/{runID}/async.",
    scenarios: ["checkpoint.async.api-payload-shape"],
    evidence: [
      {
        test: "test/unit/checkpoint-api.test.ts :: posts to /v1/checkpoint/{runId}/async",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.3.1-async-payload-shape",
    section: "10.3.1",
    title: "Async checkpoint payload contains run_id, fn_id, qi_id, steps",
    level: "MUST",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "Async checkpoint request body MUST contain run_id, fn_id, qi_id (queue item reference), and steps (StepRun opcodes).",
    scenarios: ["checkpoint.async.api-payload-shape"],
    evidence: [
      {
        test: "test/unit/checkpoint-api.test.ts :: posts correct body shape to async endpoint",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.3.1-async-bearer-auth",
    section: "10.3.1",
    title: "Async checkpoint uses hashed Bearer auth",
    level: "MUST",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "Async checkpoint requests MUST send Authorization: Bearer {hashed signing key}.",
    scenarios: ["checkpoint.async.api-bearer-auth"],
    evidence: [
      {
        test: "test/unit/checkpoint-api.test.ts :: sends bearer auth and SDK headers",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.3.1-async-200-clears-buffer",
    section: "10.3.1",
    title: "200 OK clears the buffer; checkpointed steps not re-sent in 206",
    level: "MUST",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "If the checkpoint API call succeeds, the checkpointed steps MUST be removed from the SDK's response opcode list (already persisted server-side).",
    scenarios: ["checkpoint.async.bufferedSteps-flush"],
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: bufferedSteps=2 flushes after every two steps",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.3.3-retry-behavior",
    section: "10.3.3",
    title: "Checkpoint API calls retried on transient failures",
    level: "SHOULD",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "All checkpoint API calls SHOULD be retried on transient failures (up to 5 attempts with exponential backoff and jitter).",
    scenarios: ["checkpoint.async.api-retry-exponential"],
    evidence: [
      {
        test: "test/unit/checkpoint-api.test.ts :: retries 5xx responses with exponential backoff",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.3.4-signing-key-fallback",
    section: "10.3.4",
    title: "401 triggers signing key fallback (one-way switch)",
    level: "SHOULD",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "If a checkpoint API call returns 401 Unauthorized and a fallback signing key is available, the SDK SHOULD retry with the fallback key. Once the fallback succeeds, all subsequent calls use it.",
    scenarios: ["checkpoint.async.api-401-fallback"],
    evidence: [
      {
        test: "test/unit/checkpoint-api.test.ts :: 401 triggers fallback signing key + Ref flip",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.4.1-bufferedSteps-flush",
    section: "10.4.1",
    title: "Buffer flushes when bufferedSteps reached",
    level: "MUST",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "When the buffer reaches bufferedSteps count, the SDK MUST flush all buffered steps via POST /v1/checkpoint/{runID}/async.",
    scenarios: [
      "checkpoint.async.bufferedSteps-flush",
      "checkpoint.async.bufferedSteps-1",
      "checkpoint.async.entry-conditions",
      "checkpoint.async.urlStepId-disables",
      "checkpoint.async.disable-immediate-execution",
    ],
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: bufferedSteps=2 flushes after every two steps",
        quality: "strict",
      },
      {
        test: "test/integration/checkpoint-async.test.ts :: default bufferedSteps=1 flushes after each step",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.4.1-maxInterval-flush",
    section: "10.4.1",
    title: "Buffer flushes when maxInterval elapsed",
    level: "SHOULD",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "When maxInterval time elapses since the first buffered step, the SDK SHOULD flush even if bufferedSteps not reached.",
    scenarios: ["checkpoint.async.maxInterval-flush"],
    evidence: [
      {
        test: "test/integration/checkpoint-maxRuntime.test.ts :: maxInterval triggers time-based flush",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.4.1-async-opcode-yield",
    section: "10.4.1",
    title: "Async opcode encountered: flush then yield 206",
    level: "MUST",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "If an async opcode is encountered, the SDK MUST flush any buffered steps first, then yield by returning a 206 response containing the async opcode.",
    scenarios: ["checkpoint.async.flush-on-async-opcode"],
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: flushes buffer before yielding on async opcode",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.4.1-maxRuntime-discoveryRequest",
    section: "10.4.1",
    title: "maxRuntime exceeded yields DiscoveryRequest opcode",
    level: "MUST",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "If maxRuntime is exceeded, the SDK MUST yield by returning a DiscoveryRequest opcode, telling the executor to schedule a new Call Request to continue execution.",
    scenarios: ["checkpoint.async.maxRuntime-discovery"],
    evidence: [
      {
        test: "test/integration/checkpoint-maxRuntime.test.ts :: emits DiscoveryRequest after maxRuntime",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.4.1-completion-runComplete",
    section: "10.4.1",
    title: "Completion yields RunComplete opcode",
    level: "MUST",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "When the function completes, the SDK returns a 206 response containing any remaining buffered steps plus a RunComplete opcode (TS reference behavior).",
    scenarios: [
      "checkpoint.async.flush-on-completion",
      "checkpoint.async.runComplete-shape",
      "checkpoint.async.bufferedSteps-flush",
    ],
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: appends RunComplete on successful completion",
        quality: "strict",
      },
      {
        test: "test/integration/checkpoint-async.test.ts :: RunComplete carries function return value",
        quality: "strict",
      },
    ],
  },
  {
    id: "10.4.3-graceful-fallback",
    section: "10.4.3",
    title: "Checkpoint failure MUST NOT lose step results",
    level: "MUST",
    scope: "in-scope",
    feature: "checkpointing",
    status: "covered",
    text: "If any checkpoint API call fails, the SDK MUST NOT lose step results. For async checkpointing, return the buffered steps in the standard 206 response.",
    scenarios: ["checkpoint.async.graceful-fallback-on-failure", "checkpoint.async.flush-on-step-error"],
    evidence: [
      {
        test: "test/integration/checkpoint-async.test.ts :: includes buffered steps in 206 when API fails",
        quality: "strict",
      },
    ],
  },
] as const;

export const summary = {
  excluded: excludedSpecAreas.length,
  clauses: clauses.length,
  scenarios: scenarios.length,
  byStatus: {
    covered: clauses.filter((clause) => clause.status === "covered").length,
    partial: clauses.filter((clause) => clause.status === "partial").length,
    missing: clauses.filter((clause) => clause.status === "missing").length,
    failing: clauses.filter((clause) => clause.status === "failing").length,
  },
} as const;
